framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Messenger\Message\ImportDataMessage': sync

when@dev:
    framework:
        messenger:
            transports:
                async: 'sync://'