security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_DEVICE: ROLE_USER
        ROLE_GROUP: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    providers:
        admin_user_provider:
            entity:
                class: App\Entity\Admin
                property: username

        device_user_provider:
            entity:
                class: App\Entity\Device
                property: name

        group_user_provider:
            entity:
                class: App\Entity\DeviceGroup
                property: name

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        device:
            pattern: '^/device'
            provider: device_user_provider
            entry_point: form_login

            form_login:
                login_path: device.login
                check_path: device.login

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            logout:
                path: device.logout
                target: device.login

        group:
            pattern: '^/group'
            provider: group_user_provider
            entry_point: form_login

            form_login:
                login_path: group.login
                check_path: group.login

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            logout:
                path: group.logout
                target: group.login

        admin:
            pattern: '^/admin'
            provider: admin_user_provider
            entry_point: form_login

            form_login:
                login_path: admin.login
                check_path: admin.login

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

            logout:
                path: admin.logout
                target: admin.login

    access_control:
        # Admin
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/device/login, roles: PUBLIC_ACCESS }
        - { path: ^/device, roles: ROLE_DEVICE }

        - { path: ^/group/login, roles: PUBLIC_ACCESS }
        - { path: ^/group, roles: ROLE_GROUP }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
