version: '3.4'

services:
    php:
        environment:
            APP_SECRET: ${APP_SECRET}
            APP_ENV: prod

    node:
        build:
            context: .
            target: app_node

        volumes:
            -   ./:/srv/app

        command: 'sh -c "npm install; npm run build"'
