version: '3.4'

services:
    php:
        environment:
            APP_SECRET: ${APP_SECRET}
            APP_ENV: prod

    node:
        build:
            context: .
            target: app_node

        volumes:
            -   ./:/srv/app

        command: 'sh -c "npm install; npm run build"'

    messenger:
        build:
            context: .
            target: symfony_messenger
        command: 'sh -c "php bin/console messenger:consume async"'
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        restart: unless-stopped
        depends_on:
            - php
            - database
        networks:
            - zebrina