imports:
    - { resource: 'services/' }

parameters:
    paginator.entries_per_page: 25
    app.polyline_group_time: 7200

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
